---

repos:
    - repo: https://github.com/kynan/nbstripout
      rev: 0.5.0
      hooks:
          - id: nbstripout

    - repo: https://github.com/mwouts/jupytext
      rev: v1.13.7
      hooks:
          - id: jupytext
            args: [--from, ipynb, --to, py:percent, --pipe, black] #, --pipe, isort - --treat-comment-as-code "# %%"]
            additional_dependencies:
                - black==22.3.0 # Matches hook
                - isort==5.9.3 # Matches hook

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.812
      hooks:
          - id: mypy
            args: [--no-strict-optional, --ignore-missing-imports]
            exclude: ^data_analysis/example_scripts

    - repo: local
      hooks:
          - id: unittest
            name: unittest
            entry: python -m unittest discover
            language: python
            types: [python]
            pass_filenames: false
            stages: [commit]
            additional_dependencies: [numpy, scipy, sklearn, scikit-image, matplotlib, PyQt5]

    - repo: https://github.com/pycqa/isort
      rev: 5.9.3
      hooks:
          - id: isort
            args: [--profile, black, --filter-files]
            exclude: ^data_analysis/example_scripts

    - repo: https://github.com/ambv/black
      rev: 21.9b0
      hooks:
          - id: black
            language_version: python3.9
            exclude: ^data_analysis/example_scripts

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            exclude: ^data_analysis/example_scripts

    # - repo: https://github.com/PyCQA/pydocstyle
      # rev: 6.1.1
      # hooks:
          # - id: pydocstyle

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0   # or specific tag
      hooks:
          - id: yamlfmt
            args: [--width, '150']
    # - repo: https://github.com/pre-commit/pre-commit-hooks
      # rev: v4.0.1
      # hooks:
          # # - id: fix-encoding-pragma
            # # args: [--remove] # python3 files don't use this
          # - id: check-added-large-files
            # args: [--maxkb=1000]
