'''
Icon path constants
(This is an automatically generated file, if needed, changes should be made in './icons/__init__.py)'
'''
CAMERA = 'camera.png'
CROSSHAIR = 'crosshair.png'
LASER_BLUE = 'laser_blue.png'
LED_BLUE = 'led_blue.png'
LED_GREEN = 'led_green.png'
LED_OFF = 'led_off.png'
LED_ORANGE = 'led_orange.png'
LED_RED = 'led_red.png'
LOAD = 'load.png'
PREFERENCES = 'preferences.png'
RESTART = 'restart.png'
SAVE_AS = 'save_as.png'
SETTINGS = 'settings.png'
STAGE = 'stage.png'
SWITCH_ON = 'switch_on.png'
ZOOM = 'zoom.png'
