'''
Icon path constants
(This is an automatically generated file, if needed, changes should be made in './icons/__init__.py)'
'''
CAMERA = '.\icons\camera.png'
CROSSHAIR = '.\icons\crosshair.png'
LASER_BLUE = '.\icons\laser_blue.png'
LED_BLUE = '.\icons\led_blue.png'
LED_GREEN = '.\icons\led_green.png'
LED_OFF = '.\icons\led_off.png'
LED_ORANGE = '.\icons\led_orange.png'
LED_RED = '.\icons\led_red.png'
LOAD = '.\icons\load.png'
LOG = '.\icons\log.png'
PREFERENCES = '.\icons\preferences.png'
RESTART = '.\icons\restart.png'
SAVE_AS = '.\icons\save_as.png'
SETTINGS = '.\icons\settings.png'
STAGE = '.\icons\stage.png'
SWITCH_OFF = '.\icons\switch_off.png'
SWITCH_ON = '.\icons\switch_on.png'
ZOOM = '.\icons\zoom.png'
